config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :accounts, controllers: { omniauth_callbacks: 'accounts/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # dashboard
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account
  post "unfollow/account" => "accounts#unfollow_account", as: :unfollow_account

  get "following/:username" => "accounts#following", as: :all_following
  get "followers/:username" => "accounts#followers", as: :all_followers

  get "search" => "accounts#search", as: :search

  resources :posts, only: [:new, :create, :show]
  resources :comments, only: [:create]
  resources :banners

  get "advertise" => "public#advertise", as: :advertise

  root to: "public#homepage"

end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :image, ImageUploader
  default_scope { order(start_time: :desc) }

  validates :title, presence: true
  validates :url, presence: true
  validates :image, presence: true

  scope :active, -> { where active: true }

  before_validation :set_default_duration

  def self.image_path position, limit = 1
     self.select(:id,:image,:url).where("position = ? AND start_time < ? AND end_time > ? AND active = ?", position, Time.now, Time.now, true).limit(limit)
     # x.size > 0 ? x.first : nil
  end

  def set_default_duration
    self.start_time = 1.minute.from_now unless self.start_time.present?
    self.end_time = 1.week.from_now unless self.end_time.present?
  end

end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :admin_only
  before_action :set_banner, only: [ :show, :edit, :update, :destroy ]

  def index
    @banners = Banner.active
  end

  def new
    @banner = Banner.new
  end

  def edit
  end

  def show
  end

  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      format.html {
        if @banner.save
          redirect_to banners_path, flash: { success: "New banner created" }
        else
          render action: 'new'
        end
      }
    end
  end

  def update
    if @banner.update( banner_params )
      redirect_to banners_path, flash: { success: 'Banner was successfully updated' }
    else
      render action: 'edit'
    end
  end

  def destroy
    respond_to do |format|
      if @banner.update(:active => false)
        format.json { head :no_content }
      end
    end
  end

  private

    def set_banner
      @banner = Banner.find params[:id]
    end

    def admin_only
      redirect_to dashboard_path unless account_signed_in? && current_account.is_admin == true
    end

    def banner_params
      params.require(:banner).permit( :title, :image, :url, :position, :start_time, :end_time )
    end
end

app/views/banners/_form.html.erb
<%= form_for @banner do |f| %>
  <%= render 'layouts/validation', :record => @banner %>
  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.label :title, "Title (internal use only)" %>
        <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, placeholder: "http://www.mywebsite.com", class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4">
      <div class="form-group">
        <label for="banner_position">Position</label>
        <select name="banner[position]" class="form-control" id="banner_position">
          <option value="">Please select</option>
          <option value="feed-top" <%= "selected='selected'" if @banner.position == "feed-top" %>>Feed Top</option>
          <option value="feed-sidebar" <%= "selected='selected'" if @banner.position == "feed-sidebar" %>>Feed Sidebar</option>
        </select>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3">
      <div class="form-group">
        <label for="banner_start_time">Scheduled Start</label>

        <div class="input-group date datetime-picker">
          <%= f.text_field :start_time, class: 'form-control', placeholder: "Start time", value: (@banner.start_time ? @banner.start_time.strftime('%F %H:%M') : nil) %>
          <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
      <div class="form-group">
        <label for="banner_start_time">Scheduled End</label>

        <div class="input-group date datetime-picker">
          <%= f.text_field :end_time, class: 'form-control', placeholder: "End time", value: (@banner.end_time ? @banner.end_time.strftime('%F %H:%M') : nil) %>
          <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.label :image %>
        <div>
          <%= f.file_field :image %>
        </div>
      </div>
    </div>
  </div>

  <% if @banner.image.present? %>
  <p>
    <strong>Attached image:</strong>
    <br>
    <%= image_tag @banner.image.url, width: "300" %>
  </p>
<% end %>

  <div class="row">
    <div class="col">
      <%= f.submit 'Save Banner', class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/banners/_list.html.erb
<table data-page-size="30" class="table footable">
  <thead class="hidden-xs">
    <tr>
      <th width="25%">Title</th>
      <th width="15%">Position</th>
      <th width="25%">URL</th>
      <th width="10%">Image</th>
      <th width="15%">From</th>
      <th width="10%" data-sort-ignore="true"></th>
    </tr>
  </thead>
  <tbody>
    <% @banners.each do |banner| %>
    <tr>
      <td><%= link_to banner.title, edit_banner_path(banner) %></td>
      <td><%= banner.position.split("-").last %></td>
      <td><%= banner.url %></td>
      <td><%= image_tag banner.image.thumb.url %></td>
      <td><%= banner.start_time.strftime("%d/%m/%Y") %></td>
      <td class="text-right">
        <%= link_to content_tag(:span, "", class: "fa fa-times text-dark"), banner_path(banner), data: { behaviour: 'confirm', title: "Are you sure?", text: "Click yes to delete this banner." } %>
      </td>
    </tr>
  <% end %>
  <% if @banners.size == 0 %>
    <tr>
      <td colspan="4">No banners to display.</td>
    </tr>
  <% end %>
  </tbody>
  <%#= render 'layouts/table_pagination' %>
</table>

app/views/banners/edit.html.erb
<% title "Edit Banner" %>
<% heading "Edit Banner" %>

<%= render 'form' %>

app/views/banners/index.html.erb
<% title "Banners" %>
<% heading "Banners" %>

<% content_for :page_cta do %>
  <%= link_to "New Banner", new_banner_path, class: "btn btn-success float-right" %>
<% end %>

<div class="card-box clearfix">
  <%= render "banners/list", is_active: true %>
</div>

app/views/banners/new.html.erb
<% title "New Banner" %>
<% heading "New Banner" %>

<%= render 'form' %>