config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :accounts, controllers: { omniauth_callbacks: 'accounts/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # dashboard
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account
  post "unfollow/account" => "accounts#unfollow_account", as: :unfollow_account

  get "following/:username" => "accounts#following", as: :all_following
  get "followers/:username" => "accounts#followers", as: :all_followers

  get "search" => "accounts#search", as: :search

  resources :posts, only: [:new, :create, :show]
  resources :comments, only: [:create]
  resources :banners

  get "advertise" => "public#advertise", as: :advertise

  root to: "public#homepage"

end

app/views/layouts/_account_nav.html.erb
<li class="nav-item active">
  <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
</li>
<% if is_admin? %>
<li class="nav-item">
  <%= link_to "Adverts", banners_path, class: "nav-link" %>
</li>
<% end %>
<li class="nav-item">
  <%= link_to "New Post", new_post_path, class: "nav-link" %>
</li>
<li class="nav-item">
  <%= link_to "Profile", profile_path(current_account.username), class: "nav-link" %>
</li>
<li class="nav-item">
  <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
</li>

app/views/layouts/_footer.html.erb
<p>&copy; Pixmarkt <%= DateTime.now.year %></p>

app/views/layouts/_page_heading.html.erb
<% if content_for?(:page_heading) %>
<div class="row">
  <div class="col-sm-7">
    <p class="h4 m-b-20"><%= yield :page_heading %></p>
    <% if content_for?(:page_subheading) %>
      <p class="text-muted page-title-alt"><%= yield :page_subheading %></p>
    <% end %>
  </div>

  <% if content_for?(:page_cta) %>
    <div class="col-sm-5 mb-4">
      <div class="pull-right">
        <%= yield(:page_cta) %>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/layouts/_public_nav.html.erb
<li class="nav-item active">
  <a class="nav-link" href="/">Home
    <span class="sr-only">(current)</span>
  </a>
</li>
<li class="nav-item">
  <%= link_to "Sign Up", new_account_registration_path, class: "nav-link" %>
</li>
<li class="nav-item">
  <%= link_to "Sign In", new_account_session_path, class: "nav-link" %>
</li>

app/views/layouts/_validation.html.erb
<% if local_assigns[:record] && record.errors.any? %>
  <ul class="clear text-left">
    <% record.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% elsif local_assigns[:flash]
 	errors = ""
	flash.each do |name, msg|
		msg = msg.join('</li><li>') if msg.is_a?(Array)
	  errors += "<li>#{msg}</li>" if msg.is_a?(String)
	end
  %>
  <%= "<ul class=\"validation-errors\">#{errors}</ul>".html_safe unless errors.blank? %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= tag(:meta, name: "description", content: yield(:meta_description)) if content_for?(:meta_description) %>
    <meta name="author" content="@kurucaner">

    <title><%= yield(:page_title) if content_for?(:page_title) %> Pixmarkt</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="<%= controller.controller_name %> <%= controller.action_name %> signed-<%= account_signed_in? ? 'in' : 'out' %>">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top">
      <div class="container">
        <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %>">
          Pixmarkt
        </a>

        <% if account_signed_in? %>
        <div id="search-box">
          <%= text_field_tag :search, nil, placeholder: "Search...", class: "form-control" %>
          <div id="search-results"></div>
        </div>
        <% end %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if account_signed_in? %>
              <%= render "layouts/account_nav" %>
            <% else %>
              <%= render "layouts/public_nav" %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <section class="main sunset image-with-gradient">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 inner">
            <%= render partial: "layouts/page_heading" if is_admin? %>
            <%= yield %>
          </div>
        </div>
      </div>
      <div class="gradient-overlay blue-green-gradient"></div>
    </section>

    <div class="container">
      <div class="row">
        <div class="col-lg-12 footer">
          <%= render "layouts/footer" %>
        </div>
      </div>
    </div>

    <%= yield(:page_scripts) if content_for?(:page_scripts) %>
  </body>
</html>