config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :accounts, controllers: { omniauth_callbacks: 'accounts/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # dashboard
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account
  post "unfollow/account" => "accounts#unfollow_account", as: :unfollow_account

  get "following/:username" => "accounts#following", as: :all_following
  get "followers/:username" => "accounts#followers", as: :all_followers

  get "search" => "accounts#search", as: :search

  resources :posts, only: [:new, :create, :show]
  resources :comments, only: [:create]
  resources :banners

  get "advertise" => "public#advertise", as: :advertise

  root to: "public#homepage"

end

app/models/account.rb
class Account < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :posts
  has_many :likes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

  validates :username, presence: true, uniqueness: true
  before_validation :set_username

  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    Follower.where(following_id: self.id).count
  end

  def total_following
    Follower.where(follower_id: self.id).count
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      user.username = auth.info.name.gsub(" ", "")
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  private

  def set_username
    self.username = username.downcase if username.present?
  end

end

app/controllers/accounts/omniauth_callbacks_controller.rb
class Accounts::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @account = Account.from_omniauth(request.env["omniauth.auth"])

    if @account.persisted?
      sign_in_and_redirect @account, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_account_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_account, only: [:profile, :following, :followers]

  def index
    # user dashboard - post feed
    followers_ids = Follower.where(follower_id: current_account.id).pluck(:following_id)
    followers_ids << current_account.id

    if followers_ids.size > 1
      @posts = Post.includes(:account).where(account_id: followers_ids).active.order(created_at: :desc).limit(5)
    else
      @posts = Post.includes(:account).active.order(created_at: :desc).limit(5)
    end

    @comment = Comment.new

    following_ids = Follower.where(follower_id: current_account.id).pluck(:following_id)
    following_ids << current_account.id
    @follower_suggestions = Account.where.not(id: following_ids).limit(3)

    @banner_feed_top = Banner.image_path("feed-top")
    @banner_sidebars = Banner.image_path("feed-sidebar", 1)
  end

  def load_posts
    # load new posts for inserting into feed
  end

  def search
    if params[:search]
      @accounts = Account.select(:id, :first_name, :last_name, :username, :image).where('username LIKE ?', "%#{params[:search]}%").limit(5)
    else
      # get most active accounts
      @accounts = Account.order(sign_in_count: :desc).limit(5)
    end

    respond_to do |format|
      format.js {
        render partial: "accounts/search"
      }
    end
  end

  def profile
    # user profile
    @is_follower = account_signed_in? ? Follower.where(follower_id: current_account.id, following_id: @account.id).any? : false
    @posts = @account.posts.active
  end

  def follow_account
    if Follower.create(follower_id: current_account.id, following_id: params[:follow_id])
      flash[:success] = "Now following user"
    else
      flash[:danger] = "Unable to add follower"
    end

    redirect_to dashboard_path
  end

  def unfollow_account
    connection = Follower.where(follower_id: current_account.id, following_id: params[:account_id])

    if connection.size > 0 && connection.first.destroy
      flash[:success] = "You are no longer following this user"
    else
      flash[:danger] = "Unable to unfollow this user"
    end

    redirect_to dashboard_path
  end

  def following
    ids = Follower.where(follower_id: @account.id).pluck(:following_id)
    @accounts = Account.where(id: ids)
  end

  def followers
    # get ids of users that logged in user is following
    @following_ids = account_signed_in? ? Follower.where(follower_id: current_account.id).pluck(:following_id) : []

    ids = Follower.where(following_id: @account.id).pluck(:follower_id)
    @accounts = Account.where(id: ids)
  end

  private

  def set_account
    @account = Account.find_by_username(params[:username])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def profile_picture account, width = 100
    image_path = account.image.present? ? account.image.url : "placeholder-profile.png"
    image_tag(image_path, width: width, class: "img-circle img-fluid m-r-5")
  end

  def profile_thumbnail account, width = 40, classes = "img-circle m-r-5"
    image_path = account.image.present? ? account.image.thumb.url : "placeholder-profile.png"
    image_tag(image_path, width: width, class: classes)
  end

  def can_edit_profile? profile_id
    account_signed_in? && current_account.id == profile_id
  end

  def is_admin?
    account_signed_in? && current_account.is_admin === true
  end

end

app/views/accounts/_follow.html.erb
<%= form_tag follow_account_path, method: :post, class: "float-right" do %>
  <%= hidden_field_tag :account_id, account_id %>
  <%= submit_tag "Follow user", class: "btn btn-info btn-sm text-uppercase" %>
<% end %>

app/views/accounts/_follower_suggestions.html.erb
<% @follower_suggestions.each do |account| %>
  <div class="recommended-follower">
    <div class="row">
      <div class="col-sm-3 col-lg-2">
        <%= link_to profile_picture(account, 40), profile_path(account.username) %>
      </div>
      <div class="col-sm-9 col-lg-10">
        <%= form_tag follow_account_path, method: :post, class: "float-right" do %>
          <%= hidden_field_tag :follow_id, account.id %>
          <%= submit_tag "Follow", class: "btn btn-info btn-sm" %>
        <% end %>

        <%= link_to account.username, profile_path(account.username), class: "text-dark" %>
        <p class="text-muted"><%= account.created_at > 2.days.ago ? "" : "Followed by #{ account.total_followers } #{ "user".pluralize(account.total_followers)}" %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/accounts/_search.js.erb
$("#search-results").html("<%= j render partial: 'accounts/search_results', locals: { results: @accounts } %>").show();

app/views/accounts/_search_results.html.erb
<ul class="list-unstyled">
  <% if results.size > 0 %>
    <% results.each do |account| %>
      <li>
        <%= link_to profile_path(account.username) do %>
          <%= profile_thumbnail(account, 40) %>
          <%= account.username %><br />
          <span class="text-muted"><%= account.full_name %></span>
        <% end %>
      </li>
    <% end %>
  <% else %>
    <li>No results to display.</li>
  <% end %>
</ul>

app/views/accounts/_unfollow.html.erb
<%= form_tag unfollow_account_path, method: :post, class: "float-right" do %>
  <%= hidden_field_tag :account_id, account_id %>
  <%= submit_tag "Unfollow", class: "btn btn-danger btn-sm text-uppercase" %>
<% end %>

app/views/accounts/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-lg-8 mt-4">
      <h2 class="mb-4">Followers</h2>

      <% if @accounts.size > 0 %>
        <% @accounts.each do |account| %>
          <div class="recommended-follower">
            <div class="row">
              <div class="col-2 col-lg-1">
                <%= link_to profile_picture(account, 40), profile_path(account.username) %>
              </div>
              <div class="col-10 col-lg-8">
                <% if account_signed_in? && current_account.id == @account.id %>
                  <% if @following_ids.include? account.id %>
                    <span class="btn btn-outline-secondary btn-sm disabled float-right">Following</span>
                  <% else %>
                    <%= form_tag follow_account_path, method: :post, class: "float-right" do %>
                      <%= hidden_field_tag :follow_id, account.id %>
                      <%= submit_tag "Follow Back", class: "btn btn-info btn-sm" %>
                    <% end %>
                  <% end %>
                <% end %>

                <%= link_to account.username, profile_path(account.username), class: "text-dark font-weight-bold" %>
                <p class="text-muted"><%= account.created_at > 2.days.ago ? "New User" : "Followed by #{account.total_followers} users" %></p>
              </div>
            </div>
          </div>
        <% end %>
        <% else %>
        <p>No users to display.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/accounts/following.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-lg-8 mt-4">
      <h2 class="mb-4">Following</h2>

      <% if @accounts.size > 0 %>
        <% @accounts.each do |account| %>
          <div class="recommended-follower">
            <div class="row">
              <div class="col-2 col-lg-1">
                <%= link_to profile_picture(account, 36), profile_path(account.username) %>
              </div>
              <div class="col-10 col-lg-8">
                <%= render partial: "accounts/unfollow", locals: { account_id: account.id } if account_signed_in? && current_account.id == @account.id %>

                <%= link_to account.username, profile_path(account.username), class: "text-dark font-weight-bold" %>
                <p class="text-muted"><%= account.created_at > 2.days.ago ? "New User" : "Followed by #{account.total_followers} users" %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
      <p>No users to display.</p>
    <% end %>
    </div>
  </div>
</div>

<%= link_to "View all followers", all_followers_path %>

app/views/accounts/index.html.erb
<%= title "News Feed" %>

<div class="row">
  <div class="col-lg-8" id="feed">
    <%= link_to image_tag(@banner_feed_top.image.url, class: 'img-fluid mb-3'), @banner_feed_top.url, target: "_blank" if @banner_feed_top.present? %>

    <% @posts.each do |post| %>
      <div class="insta-post">
        <div class="post-meta">
          <%= link_to profile_picture(post.account, 40), profile_path(post.account.username) %>
          <%= link_to post.account.username, profile_path(post.account.username), class: "text-dark" %>
        </div>

        <%= image_tag post.image.url, class: "img img-fluid" %>

        <div class="post-details">
          <div class="post-actions">
            <i class="fa fa-heart like-<%= post.id %> <%= 'active' if post_liked_by_user?(post.id) %> fa-2x post-like" data-id="<%= post.id %>"></i>
            <%= link_to post_path(post.id) do %>
              <i class="fa fa-comment fa-2x post-comment"></i>
            <% end %>
          </div>

          <p><strong id="post-<%= post.id %>-likes"><%= post.total_likes_count %> likes</strong></p>
          <p><strong id="post-<%= post.id %>-comments"><%= link_to post.account.username, profile_path(post.account.username), class: "text-dark" %></strong></p>

          <%= simple_format post.description %>

          <p class="text-muted"><%= time_ago_in_words post.created_at %> ago</p>

          <%= render "posts/comments", post: post, comments: Comment.includes(:account).where(post_id: post.id) %>
        </div>
        <div class="comment-box">
          <%= form_for @comment do |f| %>
            <%= f.hidden_field :post_id, value: post.id %>
            <div class="input-group">
            <%= f.text_field :comment, placeholder: "Add comment here...", class: "form-control post-comment" %>
              <div class="input-group-append">
                <%= f.submit "Post", class: "btn btn-success float-right" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if @posts.size == 0 %>
      <p>No posts to display.</p>
    <% end %>
  </div>
  <div class="col col-lg-4">
    <div class="sidebar-wrapper position-fixed">
      <div class="account-summary d-none d-lg-block">
        <p class="m-0">
          <%= link_to profile_thumbnail(current_account, 50, "img-circle float-left m-r-15"), profile_path(current_account.username) %>
          <strong><%= link_to current_account.username, profile_path(current_account.username), class: "text-dark" %></strong><br />
          <%= current_account.full_name %>
        </p>
      </div>
      <div class="follower-suggestions mb-2">
        <%= link_to "View All", "#", class: "float-right text-dark" %>
        <p class="text-muted">Suggestions for you</p>
        <%= render "accounts/follower_suggestions" %>
      </div>

      <% if @banner_sidebar.present? %>
        <div class="border mt-3 mb-2">
          <%= link_to image_tag(@banner_sidebar.image.url, class: 'img-fluid'), @banner_sidebar.url, target: "_blank" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/accounts/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= profile_picture @account, 200 %>
    </div>
    <div class="col-9 text-left">
      <div class="row">
        <div class="col">
          <% if account_signed_in? %>
            <% if can_edit_profile?(@account.id) %>
              <%= link_to "Edit Profile", edit_account_registration_path, class: "btn btn-outline-dark float-right d-none d-lg-block" %>
            <% elsif @is_follower %>
            <%= render partial: "accounts/unfollow", locals: { account_id: @account.id } %>
            <% else %>
            <%= render partial: "accounts/follow", locals: { account_id: @account.id } %>
            <% end %>
          <% end %>

          <h1><%= @account.full_name %></h1>
        </div>
      </div>

      <div class="row profile-stats">
        <div class="col-4">
          <strong><%= @account.posts.count %></strong> posts
        </div>
        <div class="col-4">
          <%= link_to all_followers_path(@account.username), class: "text-dark" do %>
            <strong><%= @account.total_followers %></strong> followers
          <% end %>
        </div>
        <div class="col-4">
          <%# if account_signed_in? && current_account.id == @account.id %>
            <%= link_to all_following_path(@account.username), class: "text-dark" do %>
              <strong><%= @account.total_following %></strong> following
            <% end %>
          <%# else %>
            <!-- <strong><%= @account.total_followers %></strong> following -->
          <%# end %>
        </div>
      </div>

      <p><%= @account.full_name %></p>
      <%= simple_format @account.description %>

      <p><%= link_to @account.website if @account.website.present? %></p>
    </div>
  </div>
  <div class="row profile-posts">
    <% @posts.each do |post| %>
      <div class="col-md-6 col-lg-4">
        <div class="insta-post post-square" style="background: url(<%= post.image.url %>) no-repeat center top">
          <%= link_to post_path(post) do %>
            <div class="post-stats">
              <div class="inner">
                <i class="fa fa-heart"></i> <%= post.total_likes_count %>
                <i class="fa fa-comment m-l-15"></i> <%= post.total_comments_count %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>